### ISSUE TITLE
WIDGET_CONFIG_TEMPLATE overlapping

### ISSUE THREAD

**Issue by bidcnichenkoalex** [iotbzh/helloworld-service#3]
https://github.com/iotbzh/helloworld-service/blob/f3917ab1134194f53f4e01d7a8cc08f7bd751a21/conf.d/cmake/config.cmake#L118

when the project compiled by "conf.d/autobuild/agl/autobuild package", mentioned variable will be overlapped by  conf.d/app-templates/cmake/cmake.d/02-variables.cmake:114. As a result *.service script which will be generated by config.xml during the installation, wouldn't be correct.

**Comment by claneys** [comment]
Yes, it is a mistake in config.cmake. I fix that !
